//
// Generated file, do not edit! Created by opp_msgtool 6.2 from mysrc/olsrv2/message/OLSRv2Packet.msg.
//

#ifndef __INET_OLSRV2PACKET_M_H
#define __INET_OLSRV2PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class Olsrv2ControlPacket;
class Olsrv2HelloPacket;
class Olsrv2TcGroup;
class Olsrv2PacketHolderMessage;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet

#include "inet/networklayer/common/L3Address_m.h" // import inet.networklayer.common.L3Address


namespace inet {

/**
 * Enum generated from <tt>mysrc/olsrv2/message/OLSRv2Packet.msg:24</tt> by opp_msgtool.
 * <pre>
 * enum Olsrv2PktType
 * {
 *     Olsrv2Hello = 1;
 *     Olsrv2Tc = 2;
 * }
 * </pre>
 */
enum Olsrv2PktType {
    Olsrv2Hello = 1,
    Olsrv2Tc = 2
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Olsrv2PktType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Olsrv2PktType& e) { int n; b->unpack(n); e = static_cast<Olsrv2PktType>(n); }

/**
 * Class generated from <tt>mysrc/olsrv2/message/OLSRv2Packet.msg:31</tt> by opp_msgtool.
 * <pre>
 * // Base type for OLSRv2 control messages
 * class Olsrv2ControlPacket extends FieldsChunk
 * {
 *     Olsrv2PktType packetType = static_cast<Olsrv2PktType>(-1);
 * }
 * </pre>
 */
class Olsrv2ControlPacket : public ::inet::FieldsChunk
{
  protected:
    Olsrv2PktType packetType = static_cast<Olsrv2PktType>(-1);

  private:
    void copy(const Olsrv2ControlPacket& other);

  protected:
    bool operator==(const Olsrv2ControlPacket&) = delete;

  public:
    Olsrv2ControlPacket();
    Olsrv2ControlPacket(const Olsrv2ControlPacket& other);
    virtual ~Olsrv2ControlPacket();
    Olsrv2ControlPacket& operator=(const Olsrv2ControlPacket& other);
    virtual Olsrv2ControlPacket *dup() const override {return new Olsrv2ControlPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual Olsrv2PktType getPacketType() const;
    virtual void setPacketType(Olsrv2PktType packetType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Olsrv2ControlPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Olsrv2ControlPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>mysrc/olsrv2/message/OLSRv2Packet.msg:37</tt> by opp_msgtool.
 * <pre>
 * // OLSRv2 HELLO message (flattened representation)
 * class Olsrv2HelloPacket extends Olsrv2ControlPacket
 * {
 *     L3Address originator;      // Originator/main address
 *     simtime_t hTime;           // HELLO interval
 *     uint8 willingness;         // RFC 7181 willingness
 *     uint16 msgSeq;             // Message sequence number
 * 
 *     // Neighbor tuples (flattened arrays)
 *     uint8 linkStatus[];        // Link status per entry
 *     uint8 neighStatus[];       // Neighbor status per entry
 *     int addrCounts[];          // Address count per entry
 *     L3Address neighAddrs[];    // Flattened neighbor interface addresses
 * }
 * </pre>
 */
class Olsrv2HelloPacket : public ::inet::Olsrv2ControlPacket
{
  protected:
    L3Address originator;
    ::omnetpp::simtime_t hTime = SIMTIME_ZERO;
    uint8_t willingness = 0;
    uint16_t msgSeq = 0;
    uint8_t *linkStatus = nullptr;
    size_t linkStatus_arraysize = 0;
    uint8_t *neighStatus = nullptr;
    size_t neighStatus_arraysize = 0;
    int *addrCounts = nullptr;
    size_t addrCounts_arraysize = 0;
    L3Address *neighAddrs = nullptr;
    size_t neighAddrs_arraysize = 0;

  private:
    void copy(const Olsrv2HelloPacket& other);

  protected:
    bool operator==(const Olsrv2HelloPacket&) = delete;

  public:
    Olsrv2HelloPacket();
    Olsrv2HelloPacket(const Olsrv2HelloPacket& other);
    virtual ~Olsrv2HelloPacket();
    Olsrv2HelloPacket& operator=(const Olsrv2HelloPacket& other);
    virtual Olsrv2HelloPacket *dup() const override {return new Olsrv2HelloPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const L3Address& getOriginator() const;
    virtual L3Address& getOriginatorForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<Olsrv2HelloPacket*>(this)->getOriginator());}
    virtual void setOriginator(const L3Address& originator);

    virtual ::omnetpp::simtime_t getHTime() const;
    virtual void setHTime(::omnetpp::simtime_t hTime);

    virtual uint8_t getWillingness() const;
    virtual void setWillingness(uint8_t willingness);

    virtual uint16_t getMsgSeq() const;
    virtual void setMsgSeq(uint16_t msgSeq);

    virtual void setLinkStatusArraySize(size_t size);
    virtual size_t getLinkStatusArraySize() const;
    virtual uint8_t getLinkStatus(size_t k) const;
    virtual void setLinkStatus(size_t k, uint8_t linkStatus);
    virtual void insertLinkStatus(size_t k, uint8_t linkStatus);
    [[deprecated]] void insertLinkStatus(uint8_t linkStatus) {appendLinkStatus(linkStatus);}
    virtual void appendLinkStatus(uint8_t linkStatus);
    virtual void eraseLinkStatus(size_t k);

    virtual void setNeighStatusArraySize(size_t size);
    virtual size_t getNeighStatusArraySize() const;
    virtual uint8_t getNeighStatus(size_t k) const;
    virtual void setNeighStatus(size_t k, uint8_t neighStatus);
    virtual void insertNeighStatus(size_t k, uint8_t neighStatus);
    [[deprecated]] void insertNeighStatus(uint8_t neighStatus) {appendNeighStatus(neighStatus);}
    virtual void appendNeighStatus(uint8_t neighStatus);
    virtual void eraseNeighStatus(size_t k);

    virtual void setAddrCountsArraySize(size_t size);
    virtual size_t getAddrCountsArraySize() const;
    virtual int getAddrCounts(size_t k) const;
    virtual void setAddrCounts(size_t k, int addrCounts);
    virtual void insertAddrCounts(size_t k, int addrCounts);
    [[deprecated]] void insertAddrCounts(int addrCounts) {appendAddrCounts(addrCounts);}
    virtual void appendAddrCounts(int addrCounts);
    virtual void eraseAddrCounts(size_t k);

    virtual void setNeighAddrsArraySize(size_t size);
    virtual size_t getNeighAddrsArraySize() const;
    virtual const L3Address& getNeighAddrs(size_t k) const;
    virtual L3Address& getNeighAddrsForUpdate(size_t k) { handleChange();return const_cast<L3Address&>(const_cast<Olsrv2HelloPacket*>(this)->getNeighAddrs(k));}
    virtual void setNeighAddrs(size_t k, const L3Address& neighAddrs);
    virtual void insertNeighAddrs(size_t k, const L3Address& neighAddrs);
    [[deprecated]] void insertNeighAddrs(const L3Address& neighAddrs) {appendNeighAddrs(neighAddrs);}
    virtual void appendNeighAddrs(const L3Address& neighAddrs);
    virtual void eraseNeighAddrs(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Olsrv2HelloPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Olsrv2HelloPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>mysrc/olsrv2/message/OLSRv2Packet.msg:52</tt> by opp_msgtool.
 * <pre>
 * // OLSRv2 TC group message (flattened representation)
 * class Olsrv2TcGroup extends Olsrv2ControlPacket
 * {
 *     simtime_t genTime;         // Generation time
 * 
 *     // Per-originator TC metadata
 *     L3Address originators[];   // Originator addresses
 *     uint16 ansns[];            // Advertised Neighbor Sequence Number
 *     uint16 seqNums[];          // Message sequence numbers
 *     uint8 hopCounts[];         // Hop count per TC
 *     int advCounts[];           // Advertised-neighbor count per TC
 * 
 *     // Flattened advertised neighbors
 *     L3Address advertisedNeighbors[];
 * }
 * </pre>
 */
class Olsrv2TcGroup : public ::inet::Olsrv2ControlPacket
{
  protected:
    ::omnetpp::simtime_t genTime = SIMTIME_ZERO;
    L3Address *originators = nullptr;
    size_t originators_arraysize = 0;
    uint16_t *ansns = nullptr;
    size_t ansns_arraysize = 0;
    uint16_t *seqNums = nullptr;
    size_t seqNums_arraysize = 0;
    uint8_t *hopCounts = nullptr;
    size_t hopCounts_arraysize = 0;
    int *advCounts = nullptr;
    size_t advCounts_arraysize = 0;
    L3Address *advertisedNeighbors = nullptr;
    size_t advertisedNeighbors_arraysize = 0;

  private:
    void copy(const Olsrv2TcGroup& other);

  protected:
    bool operator==(const Olsrv2TcGroup&) = delete;

  public:
    Olsrv2TcGroup();
    Olsrv2TcGroup(const Olsrv2TcGroup& other);
    virtual ~Olsrv2TcGroup();
    Olsrv2TcGroup& operator=(const Olsrv2TcGroup& other);
    virtual Olsrv2TcGroup *dup() const override {return new Olsrv2TcGroup(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual ::omnetpp::simtime_t getGenTime() const;
    virtual void setGenTime(::omnetpp::simtime_t genTime);

    virtual void setOriginatorsArraySize(size_t size);
    virtual size_t getOriginatorsArraySize() const;
    virtual const L3Address& getOriginators(size_t k) const;
    virtual L3Address& getOriginatorsForUpdate(size_t k) { handleChange();return const_cast<L3Address&>(const_cast<Olsrv2TcGroup*>(this)->getOriginators(k));}
    virtual void setOriginators(size_t k, const L3Address& originators);
    virtual void insertOriginators(size_t k, const L3Address& originators);
    [[deprecated]] void insertOriginators(const L3Address& originators) {appendOriginators(originators);}
    virtual void appendOriginators(const L3Address& originators);
    virtual void eraseOriginators(size_t k);

    virtual void setAnsnsArraySize(size_t size);
    virtual size_t getAnsnsArraySize() const;
    virtual uint16_t getAnsns(size_t k) const;
    virtual void setAnsns(size_t k, uint16_t ansns);
    virtual void insertAnsns(size_t k, uint16_t ansns);
    [[deprecated]] void insertAnsns(uint16_t ansns) {appendAnsns(ansns);}
    virtual void appendAnsns(uint16_t ansns);
    virtual void eraseAnsns(size_t k);

    virtual void setSeqNumsArraySize(size_t size);
    virtual size_t getSeqNumsArraySize() const;
    virtual uint16_t getSeqNums(size_t k) const;
    virtual void setSeqNums(size_t k, uint16_t seqNums);
    virtual void insertSeqNums(size_t k, uint16_t seqNums);
    [[deprecated]] void insertSeqNums(uint16_t seqNums) {appendSeqNums(seqNums);}
    virtual void appendSeqNums(uint16_t seqNums);
    virtual void eraseSeqNums(size_t k);

    virtual void setHopCountsArraySize(size_t size);
    virtual size_t getHopCountsArraySize() const;
    virtual uint8_t getHopCounts(size_t k) const;
    virtual void setHopCounts(size_t k, uint8_t hopCounts);
    virtual void insertHopCounts(size_t k, uint8_t hopCounts);
    [[deprecated]] void insertHopCounts(uint8_t hopCounts) {appendHopCounts(hopCounts);}
    virtual void appendHopCounts(uint8_t hopCounts);
    virtual void eraseHopCounts(size_t k);

    virtual void setAdvCountsArraySize(size_t size);
    virtual size_t getAdvCountsArraySize() const;
    virtual int getAdvCounts(size_t k) const;
    virtual void setAdvCounts(size_t k, int advCounts);
    virtual void insertAdvCounts(size_t k, int advCounts);
    [[deprecated]] void insertAdvCounts(int advCounts) {appendAdvCounts(advCounts);}
    virtual void appendAdvCounts(int advCounts);
    virtual void eraseAdvCounts(size_t k);

    virtual void setAdvertisedNeighborsArraySize(size_t size);
    virtual size_t getAdvertisedNeighborsArraySize() const;
    virtual const L3Address& getAdvertisedNeighbors(size_t k) const;
    virtual L3Address& getAdvertisedNeighborsForUpdate(size_t k) { handleChange();return const_cast<L3Address&>(const_cast<Olsrv2TcGroup*>(this)->getAdvertisedNeighbors(k));}
    virtual void setAdvertisedNeighbors(size_t k, const L3Address& advertisedNeighbors);
    virtual void insertAdvertisedNeighbors(size_t k, const L3Address& advertisedNeighbors);
    [[deprecated]] void insertAdvertisedNeighbors(const L3Address& advertisedNeighbors) {appendAdvertisedNeighbors(advertisedNeighbors);}
    virtual void appendAdvertisedNeighbors(const L3Address& advertisedNeighbors);
    virtual void eraseAdvertisedNeighbors(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Olsrv2TcGroup& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Olsrv2TcGroup& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>mysrc/olsrv2/message/OLSRv2Packet.msg:67</tt> by opp_msgtool.
 * <pre>
 * message Olsrv2PacketHolderMessage
 * {
 *     Packet *ownedPacket \@owned;
 * }
 * </pre>
 */
class Olsrv2PacketHolderMessage : public ::omnetpp::cMessage
{
  protected:
    Packet * ownedPacket = nullptr;

  private:
    void copy(const Olsrv2PacketHolderMessage& other);

  protected:
    bool operator==(const Olsrv2PacketHolderMessage&) = delete;

  public:
    Olsrv2PacketHolderMessage(const char *name=nullptr, short kind=0);
    Olsrv2PacketHolderMessage(const Olsrv2PacketHolderMessage& other);
    virtual ~Olsrv2PacketHolderMessage();
    Olsrv2PacketHolderMessage& operator=(const Olsrv2PacketHolderMessage& other);
    virtual Olsrv2PacketHolderMessage *dup() const override {return new Olsrv2PacketHolderMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const Packet * getOwnedPacket() const;
    virtual Packet * getOwnedPacketForUpdate() { return const_cast<Packet *>(const_cast<Olsrv2PacketHolderMessage*>(this)->getOwnedPacket());}
    virtual void setOwnedPacket(Packet * ownedPacket);
    virtual Packet * removeOwnedPacket();
    [[deprecated]] Packet * dropOwnedPacket() {return removeOwnedPacket();}
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Olsrv2PacketHolderMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Olsrv2PacketHolderMessage& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::Olsrv2ControlPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::Olsrv2ControlPacket*>(ptr.get<cObject>()); }
template<> inline inet::Olsrv2HelloPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::Olsrv2HelloPacket*>(ptr.get<cObject>()); }
template<> inline inet::Olsrv2TcGroup *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::Olsrv2TcGroup*>(ptr.get<cObject>()); }
template<> inline inet::Olsrv2PacketHolderMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::Olsrv2PacketHolderMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_OLSRV2PACKET_M_H

