//
// Generated file, do not edit! Created by opp_msgtool 6.2 from mysrc/routing/MdtRelayChunk.msg.
//

#ifndef __INET_MDTRELAYCHUNK_M_H
#define __INET_MDTRELAYCHUNK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class MdtRelayChunk;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/networklayer/common/L3Address_m.h" // import inet.networklayer.common.L3Address


namespace inet {

/**
 * Class generated from <tt>mysrc/routing/MdtRelayChunk.msg:23</tt> by opp_msgtool.
 * <pre>
 * class MdtRelayChunk extends FieldsChunk
 * {
 *     bool hasRelay;
 *     L3Address relayAddr;
 *     L3Address predAddr;
 * }
 * </pre>
 */
class MdtRelayChunk : public ::inet::FieldsChunk
{
  protected:
    bool hasRelay = false;
    L3Address relayAddr;
    L3Address predAddr;

  private:
    void copy(const MdtRelayChunk& other);

  protected:
    bool operator==(const MdtRelayChunk&) = delete;

  public:
    MdtRelayChunk();
    MdtRelayChunk(const MdtRelayChunk& other);
    virtual ~MdtRelayChunk();
    MdtRelayChunk& operator=(const MdtRelayChunk& other);
    virtual MdtRelayChunk *dup() const override {return new MdtRelayChunk(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool getHasRelay() const;
    virtual void setHasRelay(bool hasRelay);

    virtual const L3Address& getRelayAddr() const;
    virtual L3Address& getRelayAddrForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<MdtRelayChunk*>(this)->getRelayAddr());}
    virtual void setRelayAddr(const L3Address& relayAddr);

    virtual const L3Address& getPredAddr() const;
    virtual L3Address& getPredAddrForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<MdtRelayChunk*>(this)->getPredAddr());}
    virtual void setPredAddr(const L3Address& predAddr);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MdtRelayChunk& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MdtRelayChunk& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::MdtRelayChunk *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::MdtRelayChunk*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_MDTRELAYCHUNK_M_H

