//
// Generated file, do not edit! Created by opp_msgtool 6.2 from mysrc/routing/MdtRelayTag.msg.
//

#ifndef __INET_MDTRELAYTAG_M_H
#define __INET_MDTRELAYTAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class MdtRelayTag;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

#include "inet/networklayer/common/L3Address_m.h" // import inet.networklayer.common.L3Address

// cplusplus {{
#include "inet/common/TagBase_m.h"
// }}


namespace inet {

/**
 * Class generated from <tt>mysrc/routing/MdtRelayTag.msg:23</tt> by opp_msgtool.
 * <pre>
 * class MdtRelayTag extends inet::TagBase
 * {
 *     bool hasRelay = false;
 *     L3Address relayAddr;
 *     L3Address predAddr;
 * }
 * </pre>
 */
class MdtRelayTag : public ::inet::TagBase
{
  protected:
    bool hasRelay = false;
    L3Address relayAddr;
    L3Address predAddr;

  private:
    void copy(const MdtRelayTag& other);

  protected:
    bool operator==(const MdtRelayTag&) = delete;

  public:
    MdtRelayTag();
    MdtRelayTag(const MdtRelayTag& other);
    virtual ~MdtRelayTag();
    MdtRelayTag& operator=(const MdtRelayTag& other);
    virtual MdtRelayTag *dup() const override {return new MdtRelayTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool getHasRelay() const;
    virtual void setHasRelay(bool hasRelay);

    virtual const L3Address& getRelayAddr() const;
    virtual L3Address& getRelayAddrForUpdate() { return const_cast<L3Address&>(const_cast<MdtRelayTag*>(this)->getRelayAddr());}
    virtual void setRelayAddr(const L3Address& relayAddr);

    virtual const L3Address& getPredAddr() const;
    virtual L3Address& getPredAddrForUpdate() { return const_cast<L3Address&>(const_cast<MdtRelayTag*>(this)->getPredAddr());}
    virtual void setPredAddr(const L3Address& predAddr);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MdtRelayTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MdtRelayTag& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::MdtRelayTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::MdtRelayTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_MDTRELAYTAG_M_H

