//
// Generated file, do not edit! Created by opp_msgtool 6.2 from mysrc/olsr/OlsrControlPackets.msg.
//

#ifndef __INET_OLSRCONTROLPACKETS_M_H
#define __INET_OLSRCONTROLPACKETS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class OlsrControlPacket;
class OlsrHello;
class OlsrTcGroup;
class OlsrPacketHolderMessage;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet

#include "inet/networklayer/common/L3Address_m.h" // import inet.networklayer.common.L3Address


namespace inet {

/**
 * Enum generated from <tt>mysrc/olsr/OlsrControlPackets.msg:25</tt> by opp_msgtool.
 * <pre>
 * enum OlsrPktType
 * {
 *     Hello = 1;
 *     Tc = 2;
 * }
 * </pre>
 */
enum OlsrPktType {
    Hello = 1,
    Tc = 2
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OlsrPktType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OlsrPktType& e) { int n; b->unpack(n); e = static_cast<OlsrPktType>(n); }

/**
 * Class generated from <tt>mysrc/olsr/OlsrControlPackets.msg:31</tt> by opp_msgtool.
 * <pre>
 * // Base type for OLSR control messages (individual message types inherit from it)
 * class OlsrControlPacket extends FieldsChunk
 * {
 *     // no common fields here: specific message types will extend
 *     OlsrPktType packetType = static_cast<OlsrPktType>(-1);
 * }
 * </pre>
 */
class OlsrControlPacket : public ::inet::FieldsChunk
{
  protected:
    OlsrPktType packetType = static_cast<OlsrPktType>(-1);

  private:
    void copy(const OlsrControlPacket& other);

  protected:
    bool operator==(const OlsrControlPacket&) = delete;

  public:
    OlsrControlPacket();
    OlsrControlPacket(const OlsrControlPacket& other);
    virtual ~OlsrControlPacket();
    OlsrControlPacket& operator=(const OlsrControlPacket& other);
    virtual OlsrControlPacket *dup() const override {return new OlsrControlPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual OlsrPktType getPacketType() const;
    virtual void setPacketType(OlsrPktType packetType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OlsrControlPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OlsrControlPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>mysrc/olsr/OlsrControlPackets.msg:38</tt> by opp_msgtool.
 * <pre>
 * // HELLO message
 * class OlsrHello extends OlsrControlPacket
 * {
 *     // HELLO header fields
 *     L3Address originator;   // originator/main address
 *     simtime_t hTime;  // hello interval (seconds)
 *     uint8 willingness;      // 0..7
 *     uint16 msgSeq;          // per-HELLO message sequence number (for debug/dup detection)
 * 
 *     // Per-link messages flattened representation:
 *     // linkCodes[i] : 1 byte link code for i-th link message
 *     // linkCounts[i]: number of neighbor iface addresses for i-th link message
 *     uint8 linkCodes[];         // each is 1 byte in RFC
 *     int linkCounts[];          // number of addresses in that link message
 *     L3Address nbIfaceAddrs[];  // flattened neighbour-interface addresses (sum(linkCounts) entries)
 * }
 * </pre>
 */
class OlsrHello : public ::inet::OlsrControlPacket
{
  protected:
    L3Address originator;
    ::omnetpp::simtime_t hTime = SIMTIME_ZERO;
    uint8_t willingness = 0;
    uint16_t msgSeq = 0;
    uint8_t *linkCodes = nullptr;
    size_t linkCodes_arraysize = 0;
    int *linkCounts = nullptr;
    size_t linkCounts_arraysize = 0;
    L3Address *nbIfaceAddrs = nullptr;
    size_t nbIfaceAddrs_arraysize = 0;

  private:
    void copy(const OlsrHello& other);

  protected:
    bool operator==(const OlsrHello&) = delete;

  public:
    OlsrHello();
    OlsrHello(const OlsrHello& other);
    virtual ~OlsrHello();
    OlsrHello& operator=(const OlsrHello& other);
    virtual OlsrHello *dup() const override {return new OlsrHello(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const L3Address& getOriginator() const;
    virtual L3Address& getOriginatorForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<OlsrHello*>(this)->getOriginator());}
    virtual void setOriginator(const L3Address& originator);

    virtual ::omnetpp::simtime_t getHTime() const;
    virtual void setHTime(::omnetpp::simtime_t hTime);

    virtual uint8_t getWillingness() const;
    virtual void setWillingness(uint8_t willingness);

    virtual uint16_t getMsgSeq() const;
    virtual void setMsgSeq(uint16_t msgSeq);

    virtual void setLinkCodesArraySize(size_t size);
    virtual size_t getLinkCodesArraySize() const;
    virtual uint8_t getLinkCodes(size_t k) const;
    virtual void setLinkCodes(size_t k, uint8_t linkCodes);
    virtual void insertLinkCodes(size_t k, uint8_t linkCodes);
    [[deprecated]] void insertLinkCodes(uint8_t linkCodes) {appendLinkCodes(linkCodes);}
    virtual void appendLinkCodes(uint8_t linkCodes);
    virtual void eraseLinkCodes(size_t k);

    virtual void setLinkCountsArraySize(size_t size);
    virtual size_t getLinkCountsArraySize() const;
    virtual int getLinkCounts(size_t k) const;
    virtual void setLinkCounts(size_t k, int linkCounts);
    virtual void insertLinkCounts(size_t k, int linkCounts);
    [[deprecated]] void insertLinkCounts(int linkCounts) {appendLinkCounts(linkCounts);}
    virtual void appendLinkCounts(int linkCounts);
    virtual void eraseLinkCounts(size_t k);

    virtual void setNbIfaceAddrsArraySize(size_t size);
    virtual size_t getNbIfaceAddrsArraySize() const;
    virtual const L3Address& getNbIfaceAddrs(size_t k) const;
    virtual L3Address& getNbIfaceAddrsForUpdate(size_t k) { handleChange();return const_cast<L3Address&>(const_cast<OlsrHello*>(this)->getNbIfaceAddrs(k));}
    virtual void setNbIfaceAddrs(size_t k, const L3Address& nbIfaceAddrs);
    virtual void insertNbIfaceAddrs(size_t k, const L3Address& nbIfaceAddrs);
    [[deprecated]] void insertNbIfaceAddrs(const L3Address& nbIfaceAddrs) {appendNbIfaceAddrs(nbIfaceAddrs);}
    virtual void appendNbIfaceAddrs(const L3Address& nbIfaceAddrs);
    virtual void eraseNbIfaceAddrs(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OlsrHello& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OlsrHello& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>mysrc/olsr/OlsrControlPackets.msg:58</tt> by opp_msgtool.
 * <pre>
 * // OlsrTcGroup: a group-of-TC logical entries packed into one UDP packet.
 * // Inherit OLSRControlPacket 
 * class OlsrTcGroup extends OlsrControlPacket
 * {
 *     // Group-level metadata
 *     simtime_t genTime;      // generation time (simtime_t)
 *     //double vTime \@unit(s);  // validity time (VTime) in seconds - lifetime for advertised info
 *     //uint16 groupSeq;        // group sequence number (optional, for debug)
 * 
 *     // Per-TC parallel arrays (length = M logical TC entries)
 *     // Each logical TC entry represents one originator's TC: originator addr + ANSN + hopCount + count of advertised neighbors
 *     L3Address originators[]; // originator addresses (one per logical TC)
 *     uint16 ansns[];          // ANSN per originator
 *     uint16 seqNums[];        // message sequence numbers (optional; helpful for de-dup)
 *     uint8 hopCounts[];       // hopCount for each logical TC (how many hops from originator to here when created)
 *     int advCounts[];         // number of advertisedNeighbors for each logical TC
 * 
 *     // Flattened list of all advertised neighbor addresses: sum(advCounts) entries
 *     L3Address advertisedNeighbors[]; // flattened neighbor lists
 * }
 * </pre>
 */
class OlsrTcGroup : public ::inet::OlsrControlPacket
{
  protected:
    ::omnetpp::simtime_t genTime = SIMTIME_ZERO;
    L3Address *originators = nullptr;
    size_t originators_arraysize = 0;
    uint16_t *ansns = nullptr;
    size_t ansns_arraysize = 0;
    uint16_t *seqNums = nullptr;
    size_t seqNums_arraysize = 0;
    uint8_t *hopCounts = nullptr;
    size_t hopCounts_arraysize = 0;
    int *advCounts = nullptr;
    size_t advCounts_arraysize = 0;
    L3Address *advertisedNeighbors = nullptr;
    size_t advertisedNeighbors_arraysize = 0;

  private:
    void copy(const OlsrTcGroup& other);

  protected:
    bool operator==(const OlsrTcGroup&) = delete;

  public:
    OlsrTcGroup();
    OlsrTcGroup(const OlsrTcGroup& other);
    virtual ~OlsrTcGroup();
    OlsrTcGroup& operator=(const OlsrTcGroup& other);
    virtual OlsrTcGroup *dup() const override {return new OlsrTcGroup(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual ::omnetpp::simtime_t getGenTime() const;
    virtual void setGenTime(::omnetpp::simtime_t genTime);

    virtual void setOriginatorsArraySize(size_t size);
    virtual size_t getOriginatorsArraySize() const;
    virtual const L3Address& getOriginators(size_t k) const;
    virtual L3Address& getOriginatorsForUpdate(size_t k) { handleChange();return const_cast<L3Address&>(const_cast<OlsrTcGroup*>(this)->getOriginators(k));}
    virtual void setOriginators(size_t k, const L3Address& originators);
    virtual void insertOriginators(size_t k, const L3Address& originators);
    [[deprecated]] void insertOriginators(const L3Address& originators) {appendOriginators(originators);}
    virtual void appendOriginators(const L3Address& originators);
    virtual void eraseOriginators(size_t k);

    virtual void setAnsnsArraySize(size_t size);
    virtual size_t getAnsnsArraySize() const;
    virtual uint16_t getAnsns(size_t k) const;
    virtual void setAnsns(size_t k, uint16_t ansns);
    virtual void insertAnsns(size_t k, uint16_t ansns);
    [[deprecated]] void insertAnsns(uint16_t ansns) {appendAnsns(ansns);}
    virtual void appendAnsns(uint16_t ansns);
    virtual void eraseAnsns(size_t k);

    virtual void setSeqNumsArraySize(size_t size);
    virtual size_t getSeqNumsArraySize() const;
    virtual uint16_t getSeqNums(size_t k) const;
    virtual void setSeqNums(size_t k, uint16_t seqNums);
    virtual void insertSeqNums(size_t k, uint16_t seqNums);
    [[deprecated]] void insertSeqNums(uint16_t seqNums) {appendSeqNums(seqNums);}
    virtual void appendSeqNums(uint16_t seqNums);
    virtual void eraseSeqNums(size_t k);

    virtual void setHopCountsArraySize(size_t size);
    virtual size_t getHopCountsArraySize() const;
    virtual uint8_t getHopCounts(size_t k) const;
    virtual void setHopCounts(size_t k, uint8_t hopCounts);
    virtual void insertHopCounts(size_t k, uint8_t hopCounts);
    [[deprecated]] void insertHopCounts(uint8_t hopCounts) {appendHopCounts(hopCounts);}
    virtual void appendHopCounts(uint8_t hopCounts);
    virtual void eraseHopCounts(size_t k);

    virtual void setAdvCountsArraySize(size_t size);
    virtual size_t getAdvCountsArraySize() const;
    virtual int getAdvCounts(size_t k) const;
    virtual void setAdvCounts(size_t k, int advCounts);
    virtual void insertAdvCounts(size_t k, int advCounts);
    [[deprecated]] void insertAdvCounts(int advCounts) {appendAdvCounts(advCounts);}
    virtual void appendAdvCounts(int advCounts);
    virtual void eraseAdvCounts(size_t k);

    virtual void setAdvertisedNeighborsArraySize(size_t size);
    virtual size_t getAdvertisedNeighborsArraySize() const;
    virtual const L3Address& getAdvertisedNeighbors(size_t k) const;
    virtual L3Address& getAdvertisedNeighborsForUpdate(size_t k) { handleChange();return const_cast<L3Address&>(const_cast<OlsrTcGroup*>(this)->getAdvertisedNeighbors(k));}
    virtual void setAdvertisedNeighbors(size_t k, const L3Address& advertisedNeighbors);
    virtual void insertAdvertisedNeighbors(size_t k, const L3Address& advertisedNeighbors);
    [[deprecated]] void insertAdvertisedNeighbors(const L3Address& advertisedNeighbors) {appendAdvertisedNeighbors(advertisedNeighbors);}
    virtual void appendAdvertisedNeighbors(const L3Address& advertisedNeighbors);
    virtual void eraseAdvertisedNeighbors(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OlsrTcGroup& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OlsrTcGroup& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>mysrc/olsr/OlsrControlPackets.msg:77</tt> by opp_msgtool.
 * <pre>
 * message OlsrPacketHolderMessage//for delay send
 * {
 *     Packet *ownedPacket \@owned;
 * }
 * </pre>
 */
class OlsrPacketHolderMessage : public ::omnetpp::cMessage
{
  protected:
    Packet * ownedPacket = nullptr;

  private:
    void copy(const OlsrPacketHolderMessage& other);

  protected:
    bool operator==(const OlsrPacketHolderMessage&) = delete;

  public:
    OlsrPacketHolderMessage(const char *name=nullptr, short kind=0);
    OlsrPacketHolderMessage(const OlsrPacketHolderMessage& other);
    virtual ~OlsrPacketHolderMessage();
    OlsrPacketHolderMessage& operator=(const OlsrPacketHolderMessage& other);
    virtual OlsrPacketHolderMessage *dup() const override {return new OlsrPacketHolderMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const Packet * getOwnedPacket() const;
    virtual Packet * getOwnedPacketForUpdate() { return const_cast<Packet *>(const_cast<OlsrPacketHolderMessage*>(this)->getOwnedPacket());}
    virtual void setOwnedPacket(Packet * ownedPacket);
    virtual Packet * removeOwnedPacket();
    [[deprecated]] Packet * dropOwnedPacket() {return removeOwnedPacket();}
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OlsrPacketHolderMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OlsrPacketHolderMessage& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::OlsrControlPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::OlsrControlPacket*>(ptr.get<cObject>()); }
template<> inline inet::OlsrHello *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::OlsrHello*>(ptr.get<cObject>()); }
template<> inline inet::OlsrTcGroup *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::OlsrTcGroup*>(ptr.get<cObject>()); }
template<> inline inet::OlsrPacketHolderMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::OlsrPacketHolderMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_OLSRCONTROLPACKETS_M_H

